// Code generated by MockGen. DO NOT EDIT.
// Source: calculation.go

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCalculation is a mock of Calculation interface.
type MockCalculation struct {
	ctrl     *gomock.Controller
	recorder *MockCalculationMockRecorder
}

// MockCalculationMockRecorder is the mock recorder for MockCalculation.
type MockCalculationMockRecorder struct {
	mock *MockCalculation
}

// NewMockCalculation creates a new mock instance.
func NewMockCalculation(ctrl *gomock.Controller) *MockCalculation {
	mock := &MockCalculation{ctrl: ctrl}
	mock.recorder = &MockCalculationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculation) EXPECT() *MockCalculationMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCalculation) Add(a, b int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCalculationMockRecorder) Add(a, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCalculation)(nil).Add), a, b)
}
